ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER SUM3_BDR IDENTIFIED BY ASDF1234
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE ANY VIEW, DROP ANY VIEW TO SUM3_BDR;

create SYNONYM municipios for sum3_bdr.municipalidades; 
create SYNONYM juzgado for sum3_bdr.juzgados_policia_local; 
create SYNONYM funcionario for sum3_bdr.funcionarios_muinicipales; 

CREATE USER ejemplo3 IDENTIFIED BY ejemplo3
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE ANY VIEW, DROP ANY VIEW TO ejemplo3;