CREATE OR REPLACE PROCEDURE SUMA_VALORES(TOTAL OUT NUMBER) IS
  BEGIN
  SELECT SUM(PRECIO) INTO TOTAL
  FROM VEHICULO;
END;
/

SET SERVEROUTPUT ON;
DECLARE
  TOTAL NUMBER;
BEGIN
  SUMA_VALORES(TOTAL);
  DBMS_OUTPUT.PUT_LINE(TRIM(TO_CHAR(TOTAL,'$999G999G999G999G999G999G999')));
END;

CREATE OR REPLACE PROCEDURE SUMA_VALORES_ANIO(VALOR IN OUT NUMBER,
                                              CANTIDAD OUT NUMBER) IS
BEGIN
   CANTIDAD := 0;
   SELECT SUM(PRECIO), COUNT(ID_VEHICULO) INTO VALOR, CANTIDAD
   FROM VEHICULO
   WHERE ANO = VALOR
   GROUP BY ANO;
END;
/

DECLARE
  TOTAL NUMBER;
  CANTIDAD NUMBER;
BEGIN
  TOTAL := 2009;
  SUMA_VALORES_ANIO(TOTAL,CANTIDAD);
  DBMS_OUTPUT.PUT_LINE(TRIM(TO_CHAR(TOTAL,'$999G999G999G999G999G999G999')));
  DBMS_OUTPUT.PUT_LINE(CANTIDAD);
END;

CREATE OR REPLACE PROCEDURE VENTAS_SUCURSAL(V_ID_SUCURSAL IN SUCURSAL.ID_SUCURSAL%TYPE,
                                            ANIO IN NUMBER,
                                            TOTAL_VENTAS OUT NUMBER,
                                            CANTIDAD_VENTAS OUT NUMBER) IS

  CURSOR C1 IS SELECT COM.VALOR VALOR
               FROM SUCURSAL S INNER JOIN CLIENTE C 
                    ON S.ID_SUCURSAL = C.ID_SUCURSAL INNER JOIN COMPRA COM
                    ON COM.RUT = C.RUT
               WHERE S.ID_SUCURSAL = V_ID_SUCURSAL
                    AND EXTRACT(YEAR FROM COM.FECHA) = ANIO;
BEGIN
  TOTAL_VENTAS := 0;
  CANTIDAD_VENTAS := 0;
  FOR REGISTRO IN C1 LOOP
    TOTAL_VENTAS := TOTAL_VENTAS + REGISTRO.VALOR;
    CANTIDAD_VENTAS := CANTIDAD_VENTAS + 1;
  END LOOP;
END;
/


DECLARE
  V_ID_SUCURSAL SUCURSAL.ID_SUCURSAL%TYPE;
  ANIO NUMBER;
  TOTAL_VENTAS NUMBER;
  CANTIDAD_VENTAS NUMBER;
BEGIN
  V_ID_SUCURSAL := '&INGRESE_ID_SUCURSAL';
  ANIO := '&INGRESE_A�O';
  
  VENTAS_SUCURSAL(V_ID_SUCURSAL, ANIO, TOTAL_VENTAS, CANTIDAD_VENTAS);
  DBMS_OUTPUT.PUT_LINE('LA SUCURSAL: '||V_ID_SUCURSAL);
  DBMS_OUTPUT.PUT_LINE('EL A�O: '||ANIO);
  DBMS_OUTPUT.PUT_LINE('VENDIO UN TOTAL DE '||TRIM(TO_CHAR(TOTAL_VENTAS,'$999G999G999G999G999')));
  DBMS_OUTPUT.PUT_LINE('EN '||CANTIDAD_VENTAS||' VENTAS');
EXCEPTION
  WHEN VALUE_ERROR THEN
    DBMS_OUTPUT.PUT_LINE('DEBE INGRESAR SOLO VALORES NUMERICOS');
  WHEN INVALID_NUMBER THEN
    DBMS_OUTPUT.PUT_LINE('EL NUMERO INGRESADO NO ES CONVERTIBLE');
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('SE HA PRODUCIDO UN ERROR DESCONOCIDO');
END;
/


CREATE OR REPLACE PROCEDURE MUESTRA_AUTOMOTORAS AS
  CURSOR C1 IS SELECT COUNT(A.RUT_EMPRESA) CANTIDAD_VENTAS,
                      A.RUT_EMPRESA RUT, A.NOMBRE NOMBRE
               FROM AUTOMOTORA A INNER JOIN SUCURSAL S
                    ON A.RUT_EMPRESA = S.RUT_EMPRESA INNER JOIN CLIENTE C
                    ON C.ID_SUCURSAL = S.ID_SUCURSAL INNER JOIN COMPRA COM
                    ON C.RUT = COM.RUT
                    GROUP BY A.RUT_EMPRESA, A.NOMBRE
                    ORDER BY A.RUT_EMPRESA ASC;

  REGISTRO C1%ROWTYPE;
BEGIN
  OPEN C1;
  LOOP
    FETCH C1 INTO REGISTRO;
    EXIT WHEN C1%NOTFOUND;
    
    DBMS_OUTPUT.PUT_LINE('======================================');
    DBMS_OUTPUT.PUT_LINE('RUT AUTOMOTORA: '||REGISTRO.RUT);
    DBMS_OUTPUT.PUT_LINE('NOMBRE: '||REGISTRO.NOMBRE);
    DBMS_OUTPUT.PUT_LINE('CANTIDAD DE VENTAS: '||REGISTRO.CANTIDAD_VENTAS);
    DBMS_OUTPUT.PUT_LINE('======================================');
  END LOOP;
  CLOSE C1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE HAN ENCONTRADO DATOS');
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('HA OCURRIDO UN ERROR DESCONOCIDO');
END MUESTRA_AUTOMOTORAS;
/


SET SERVEROUTPUT ON;
EXEC MUESTRA_AUTOMOTORAS;


CREATE OR REPLACE PROCEDURE REBAJA_PRECIOS(ANNO IN NUMBER, REBAJA IN NUMBER) IS
  CURSOR C1 IS SELECT ID_VEHICULO FROM VEHICULO WHERE ANO < ANNO;
  V_ID_VEHICULO VEHICULO.ID_VEHICULO%TYPE;
  
  REBAJA_NO_VALIDA EXCEPTION;
BEGIN
  IF REBAJA < 0 OR REBAJA > 99 THEN
    RAISE REBAJA_NO_VALIDA;
  END IF;
   OPEN C1;
   
   LOOP
    FETCH C1 INTO V_ID_VEHICULO;
    EXIT WHEN C1%NOTFOUND;
    
    UPDATE VEHICULO
    SET PRECIO = ROUND(PRECIO * (REBAJA/100))
    WHERE ID_VEHICULO = V_ID_VEHICULO;
  END LOOP;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE HAN ENCONTRADO DATOS');
  WHEN REBAJA_NO_VALIDA THEN
    DBMS_OUTPUT.PUT_LINE('LA REBAJA SOLO PUEDE SER ENTRE 1 Y 99');
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('HA OCURRIDO UN ERROR DESCONOCIDO');
END REBAJA_PRECIOS;
/


SELECT PRECIO, PATENTE
FROM VEHICULO
ORDER BY PATENTE ASC;

EXEC REBAJA_PRECIOS(2010,10);

SELECT PRECIO, PATENTE
FROM VEHICULO
ORDER BY PATENTE ASC;

CREATE OR REPLACE PROCEDURE SUMA_VALORES(TOTAL OUT NUMBER) IS
  BEGIN
  SELECT SUM(PRECIO) INTO TOTAL
  FROM VEHICULO;
END;
/


SET SERVEROUTPUT ON;
DECLARE
  TOTAL NUMBER;
BEGIN
  SUMA_VALORES(TOTAL);
  DBMS_OUTPUT.PUT_LINE(TRIM(TO_CHAR(TOTAL,'$999G999G999G999G999G999G999')));
END;

CREATE OR REPLACE PROCEDURE SUMA_VALORES_ANIO(VALOR IN OUT NUMBER,
                                              CANTIDAD OUT NUMBER) IS
BEGIN
   CANTIDAD := 0;
   SELECT SUM(PRECIO), COUNT(ID_VEHICULO) INTO VALOR, CANTIDAD
   FROM VEHICULO
   WHERE ANO = VALOR
   GROUP BY ANO;
END;
/

DECLARE
  TOTAL NUMBER;
  CANTIDAD NUMBER;
BEGIN
  TOTAL := 2009;
  SUMA_VALORES_ANIO(TOTAL,CANTIDAD);
  DBMS_OUTPUT.PUT_LINE(TRIM(TO_CHAR(TOTAL,'$999G999G999G999G999G999G999')));
  DBMS_OUTPUT.PUT_LINE(CANTIDAD);
END;

CREATE OR REPLACE PROCEDURE VENTAS_SUCURSAL(V_ID_SUCURSAL IN SUCURSAL.ID_SUCURSAL%TYPE,
                                            ANIO IN NUMBER,
                                            TOTAL_VENTAS OUT NUMBER,
                                            CANTIDAD_VENTAS OUT NUMBER) IS

  CURSOR C1 IS SELECT COM.VALOR VALOR
               FROM SUCURSAL S INNER JOIN CLIENTE C 
                    ON S.ID_SUCURSAL = C.ID_SUCURSAL INNER JOIN COMPRA COM
                    ON COM.RUT = C.RUT
               WHERE S.ID_SUCURSAL = V_ID_SUCURSAL
                    AND EXTRACT(YEAR FROM COM.FECHA) = ANIO;
BEGIN
  TOTAL_VENTAS := 0;
  CANTIDAD_VENTAS := 0;
  FOR REGISTRO IN C1 LOOP
    TOTAL_VENTAS := TOTAL_VENTAS + REGISTRO.VALOR;
    CANTIDAD_VENTAS := CANTIDAD_VENTAS + 1;
  END LOOP;
END;
/


DECLARE
  V_ID_SUCURSAL SUCURSAL.ID_SUCURSAL%TYPE;
  ANIO NUMBER;
  TOTAL_VENTAS NUMBER;
  CANTIDAD_VENTAS NUMBER;
BEGIN
  V_ID_SUCURSAL := '&INGRESE_ID_SUCURSAL';
  ANIO := '&INGRESE_A�O';
  
  VENTAS_SUCURSAL(V_ID_SUCURSAL, ANIO, TOTAL_VENTAS, CANTIDAD_VENTAS);
  DBMS_OUTPUT.PUT_LINE('LA SUCURSAL: '||V_ID_SUCURSAL);
  DBMS_OUTPUT.PUT_LINE('EL A�O: '||ANIO);
  DBMS_OUTPUT.PUT_LINE('VENDIO UN TOTAL DE '||TRIM(TO_CHAR(TOTAL_VENTAS,'$999G999G999G999G999')));
  DBMS_OUTPUT.PUT_LINE('EN '||CANTIDAD_VENTAS||' VENTAS');
EXCEPTION
  WHEN VALUE_ERROR THEN
    DBMS_OUTPUT.PUT_LINE('DEBE INGRESAR SOLO VALORES NUMERICOS');
  WHEN INVALID_NUMBER THEN
    DBMS_OUTPUT.PUT_LINE('EL NUMERO INGRESADO NO ES CONVERTIBLE');
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('SE HA PRODUCIDO UN ERROR DESCONOCIDO');
END;
/



