--LENGTH -> RECIBE UN TEXTO(CHAR, NCHAR, VARCHAR, NVARCHAR, CLOB, NCLOB) -> RETORNA UN NUMERO
SELECT LENGTH(NOMBRE) 
FROM REGION
WHERE NOMBRE LIKE'%TARAPA%';

SELECT LENGTH(1212121)
FROM DUAL;

-- SUBSTR -> RECIBE TEXTO, NUMERO POSICION, NUMERO CANTIDAD CARACTERES -> RETORNA TEXTO
SELECT SUBSTR('C?sar Guti?rrez',15,3)
FROM DUAL;

-- ROUND -> RECIBE UN NUMBER -> RETORNA UN NUMBER SIN DECIMALES REDONDEADO
SELECT SUBSTR('C?sar Guti?rrez',ROUND(LENGTH('C?sar Guti?rrez')/2),1)
FROM DUAL;

-- ROUND -> RECIBE UN NUMBER -> RETORNA UN NUMBER CON LA CANTIDAD DE DECIMALES INGRESADA REDONDEADO
SELECT ROUND(1234.28736487265826,5)
FROM DUAL;

-- TRUNC -> RECIBE UN NUMBER -> RETORNA UN NUMBER CON LA CANTIDA DE DECIMALES TRUNCADOS
SELECT TRUNC(1234.8736487265826)
FROM DUAL;

-- TRUNC -> RECIBE UN NUMBER -> RETORNA UN NUMBER CON LA CANTIDAD DE DECIMALES INGRESADA TRUNCADOS
SELECT TRUNC(1234.8736487265826,3)
FROM DUAL;

-- TRIM -> RECIBE UN TEXTO -> RETORNA ES EL TEXTO SIN ESPACIOS LATERALES
SELECT TRIM('          UN TEXTO DE EJEMPLO         ')
FROM DUAL;

SELECT TRIM(BOTH ' ' FROM '          UN TEXTO DE EJEMPLO         ')
FROM DUAL;
-- QUITA ESPACIO A LA IZQUIERA
SELECT TRIM(LEADING ' ' FROM '          UN TEXTO DE EJEMPLO         ')
FROM DUAL;
-- QUITA ESPACIOS A LA DERECHA
SELECT TRIM(TRAILING ' ' FROM '          UN TEXTO DE EJEMPLO         ')
FROM DUAL;
-- QUITAR UNA LETRA EN ESPECIFICO
SELECT TRIM( 'U' FROM 'UN TEXTO DE EJEMPLO')
FROM DUAL;
-- CASTEA TEXTO (CASI NUNCA SE USA --- NUNCA)
SELECT TRIM(CAST (NULL AS CHAR(1)) FROM 'ABC')
FROM DUAL;

-- LPAD -> RECIBE TEXTO, NUMBER -> RETORNA TEXTO CON CANTIDAD DE CARACTERES DE RELLENO A LA IZQUIERDA
SELECT LPAD('HOLA MUNDO',45)
FROM DUAL;

SELECT LPAD('HOLA MUNDO',45,'?')
FROM DUAL;

-- RPAD -> RECIBE TEXTO, NUMBER -> RETORNA TEXTO CON CANTIDAD DE CARACTERES DE RELLENO A LA DERECHA

SELECT RPAD('HOLA MUNDO',45)
FROM DUAL;

SELECT RPAD('HOLA MUNDO',45,'?')
FROM DUAL;

SELECT LPAD((RPAD('HOLA MUNDO',15,'?')),20,'?')
FROM DUAL;

--- UPPER -> RECIBE TEXTO -> RETORNA TEXTO EN MAYUSCULAS
SELECT UPPER('este es un texto en minusculas')
FROM DUAL;

-- LOWER -> RECIBE TEXTO -> RETORNA TEXTO EN MINUSCULAS
SELECT LOWER('ESTE ES UN TEXTO EN MAYUSCULAS')
FROM DUAL;

-- CONCAT 
SELECT CONCAT('TEXTO1','TEXTO2')
FROM DUAL;

SELECT CONCAT(CONCAT('TEXTO1','TEXTO2'),'TEXTO3')
FROM DUAL;

SELECT 'TEXTO1'||'TEXTO2'||'TEXTO3'
FROM DUAL;

-- TO_NUMBER -> RECIBE UN NUMERO O TEXTO -> RETORNA UN NUMBER
SELECT TO_NUMBER('17717171')
FROM DUAL;

SELECT TO_NUMBER('12E8')
FROM DUAL;

SELECT TO_NUMBER('125.00','999.99')
FROM DUAL;

------------------22-10-2021
TO_CHAR--> Cadena de caracteres //recibe date y numeros -->retorna texto

SELECT  SYSDATE FROM DUAL;-->OBTENCION DE DATE CON SYSDATE

SELECT  LENGTH(SYSDATE) FROM DUAL;

SELECT  TO_CHAR(SYSDATE, 'DD-MM-YYYY') FROM DUAL;
SELECT  TO_CHAR(SYSDATE, 'DD-MONTH-YYYY') FROM DUAL;-->obtener fecha en formato especifico
SELECT  TO_CHAR(SYSDATE, 'DD-Mon-YYYY') FROM DUAL;-->obtener fecha en formato especifico

SELECT  TO_CHAR(SYSDATE, 'DD-MM-YYYY') FROM DUAL;
SELECT  TO_CHAR(SYSDATE, 'DDD') FROM DUAL;--->OBTENER DIA ESPECIFICO DEL AÑO

SELECT  TO_CHAR(SYSDATE, 'HH24') FROM DUAL;-->OBTENER HORA DEL DIA
SELECT  TO_CHAR(SYSDATE, 'MI') FROM DUAL; -->OBTENER MINUTO DE LA HORA

SELECT (TO_NUMBER( TO_CHAR(SYSDATE, 'DDD'))*24)+ TO_NUMBER(TO_CHAR(SYSDATE, 'HH24') ) FROM DUAL;-->CANTIDAD DE HORAS EN EL AÑO




SELECT TO_CHAR(125.25,'000099')
FROM DUAL;

SELECT TO_CHAR(125.25,'000099.99')
FROM DUAL;

SELECT TO_CHAR(12509876567,'FM99,999,999,999,999')
FROM DUAL;

---TO_DATE--> CONVIERTE UNA FECHA= RECIBE UN TEXTO Y UN FORMATO DE FECHA--ETORNA UNA FECHA

SELECT TO_DATE('111111','YYDDMM')
FROM DUAL;

SELECT TO_CHAR(TO_DATE('111111','YYDDMM'),'DD-MONTH-YYYY')
FROM DUAL;

SELECT TO_CHAR(TO_DATE('111111','YYDDMM'),'DD-MONTH-YYYY')
FROM DUAL;

SELECT TO_DATE('11/20/2030','DDMMYYYY')
FROM DUAL;

SELECT TO_DATE('11_20_2030','DD.MM.YYYY')
FROM DUAL;

SELECT TO_DATE('11.20.2030','DD.MM.YYYY')
FROM DUAL;

SELECT TO_DATE('11.20.2030','DD.MM.Y')
FROM DUAL;

---MONTH_BETWEEN --RECIBE 2 FECHAS Y RETONA UN NUMERO(CANTIDAD DE MESES ENTRE LAS FECHAS)

SELECT MONTHS_BETWEEN(SYSDATE,TO_DATE('01010001','DDMMYYYY'))
FROM DUAL;

---FUNCIONES DE FECHAS

--ADD_MONTHS=> FECHA Y NUMERO Y RETORNA LA FECHA CON LA CANTIDAD DE MESES INDICADA EN EL NUMERO

SELECT ADD_MONTHS(SYSDATE,30)
FROM DUAL;

--NEXT_DAY=> OBTINE EL DIA SIG DE UN DIA EN ESPECIFICO
			--RECIBE FECHA Y UN TEXTO= RETORNANDO EL PROXIMO DIA INDICADO EN EL TEXTO

SELECT NEXT_DAY(SYSDATE,'DOMINGO')
FROM DUAL;

SELECT NEXT_DAY(SYSDATE,'MIÉRCOLES')
FROM DUAL;

--LAST_DAY=> RECIBE FECHA Y UN TEXTO--> RETORNA LA FECHA DEL ULTIMO DIA DEL MESES


SELECT LAST_DAY(SYSDATE)
FROM DUAL;

SELECT NEXT_DAY(SYSDATE-7,'MIÉRCOLES')
FROM DUAL;

---EXTRAC=> ELEMENTO A EXTRAER DESDE LA FECHA --> RETORNA EL ELEMENTO SOLICITADO DE LA FECHA
SELECT EXTRACT(YEAR FROM SYSDATE)
FROM DUAL;

SELECT EXTRACT(MONTH FROM SYSDATE)
FROM DUAL;

SELECT EXTRACT(DAY FROM SYSDATE)
FROM DUAL;

----ROUND EN FECHA => RECIBE UNA FECHA Y UNA PORCION DE LA FECHA -->ETORNA LA FECHA REDONDEADA

SELECT ROUND(SYSDATE,'YEAR')
FROM DUAL;

SELECT ROUND(SYSDATE,'MONTH')
FROM DUAL;

SELECT ROUND (TO_DATE('021122020','MMDDYYYY','YEAR'))
FROM DUAL;


SELECT ROUND(TO_DATE('021122020','MMDDYYYY','MONTH'))
FROM DUAL;


----TRUNC

SELECT TRUNC(SYSDATE,'YEAR')
FROM DUAL;

SELECT TRUNC(SYSDATE,'MONTH')
FROM DUAL;

SELECT TRUNC (TO_DATE('021122020','MMDDYYYY','YEAR'))
FROM DUAL;


SELECT TRUNC(TO_DATE('021122020','MMDDYYYY','MONTH'))
FROM DUAL;

---
SELECT SYSDAY FROM DUAL;---BUSCAR QUE ES


---REPLACE=> RECIBE 3 TEXTOS--> REEMPLAZA DEL PRIMER TEXTO EL SEGUNDO TEXTO POR EL TERCER TEXTO

SELECT REPLACE(NOM_VENDEDOR, 'A','Z')
FROM VENDEDOR;

SELECT REPLACE(NOM_VENDEDOR, 'el','Z')
FROM VENDEDOR;

SELECT REPLACE('Negid', 'egid','a')
FROM dual;
     
---TRANSLATE => RECIBIR 3 TEXTOS -->REEMPLAZA DEL PRIMER TEXTO Y TOMA LA EQUIVALENCIA DEL SEGUNDO TEXTO PARA CONVERTIRLO DE ACUERDO AL TERCER TEXTO

SELECT TRANSLATE(NOM_VENDEDOR,ÁÉÍÓÚáéíóú,AEIOUaeiou)
FROM VENDEDOR;

SELECT TRANSLATE(NOM_VENDEDOR,'Ññ','Nn')
FROM VENDEDOR;

---INSTR=>RECIBIMOS DOS TEXTOS -->RETORNA EL NUMERO DE LA POSICION EN LA QUE SE ENCUENTRA EL SEGUNDO TEXTO
SELECT INSTR('NEGID INATI','I')
FROM DUAL; 

SELECT INSTR('NEGID INATI','TI')
FROM DUAL; 

---INITCAP=>RECIBE UN TEXTO-->RETORNA EL MISMO TEXTO PERO CON SUS PRIMERAS LETRAS EN MAYUSCULO

SELECT INITCAP('negidi...animo que tu puedes!')
FROM DUAL;

---NVL

SELECT NVL(TO_CHAR(MANAGER_ID,'SIN MANAGER'), DEPARTMENT_ID)
FROM DEPARTAMENTS;

---DECODE

SELECT DECODE(MANAGER_ID,NULL,0,1), DEPARTMENT_ID
FROM DEPARTAMENTS;


---COALESCE=COMPARA ENTRE DOS ELEMENTOS Y VERIFICAN SI LOS ELECMENTOS TIENE UN NULO,//LOS ELEMENTOS DEBEN SER DEL MISMO TIPO
			--SI LOS DOS ELEMENTOS TIENEN null, MUESTRA NULL
			--SI UNO DE LOS DOS ES NULL, MUESTRA NULL
			--SI AMBOS NO SON NULOS, MUESTRA EL PRIMER ELEMENTO
SELECT COALESCE(MANAGER_ID,COMMISSION_PCT)
FROM EMPLOYEES;

---CASE
SELECT COUNTRY_NAME,CASE REGION_ID 
WHEN 1 THEN 'EURAPA'
WHEN 2 THEN 'SUDAMERICA'
ELSE 'NO ME IMPORTA' END
FROM COUNTRIES;

---MOD=>DEBUELVE EL RESTO DE UNA OPERACION

SELECT MOD(7,2)
FROM DUAL;


SELECT REGION_ID,COUNTRY_NAME
FROM COUNTRIES
WHERE MOD(REGION_ID,2)=0;



